baseURL = 'https://blog.cfanguo.me/'
languageCode = 'en-us'
title = 'See Fan Go'
theme = "archie"

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	subtitle = "A mostly non-tech blog about travel, food, fitness and reviews"
  favicon = "favicon.ico"
  customcss = ["css/customize.css"]

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/cfan-guo"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/gofango/"

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://instagram.com/cfan.guo/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3
